fixtures:
  repositories:
    'inifile': 'git://github.com/puppetlabs/puppetlabs-inifile'
    'keystone':
      repo: 'git://github.com/stackforge/puppet-keystone.git'
      ref: 'stable/havana'
    'mysql': 'git://github.com/puppetlabs/puppetlabs-mysql.git'
    'nova':
      repo: 'git://github.com/stackforge/puppet-nova.git'
      ref: 'stable/havana'
    'stdlib': 'git://github.com/puppetlabs/puppetlabs-stdlib.git'
  symlinks:
    'ceilometer': "#{source_dir}"
